"""empty message

Revision ID: 580f69480e97
Revises: None
Create Date: 2019-06-16 21:24:44.149501

"""

# revision identifiers, used by Alembic.
revision = '580f69480e97'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('cards')
    op.drop_table('events')
    op.drop_table('controllers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controllers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('serial', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fw', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conn_fw', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('last_conn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('license', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interval', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='controllers_pkey')
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('flags', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('flags', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tz', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cards_pkey')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('serial', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    # ### end Alembic commands ###
