"""empty message

Revision ID: 654736a32001
Revises: a62a425869c7
Create Date: 2019-07-03 10:13:49.771355

"""

# revision identifiers, used by Alembic.
revision = '654736a32001'
down_revision = 'a62a425869c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('events', 'readable_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('readable_time', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('events', 'time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
