"""empty message

Revision ID: a62a425869c7
Revises: ef60b0d825aa
Create Date: 2019-07-02 11:32:27.126940

"""

# revision identifiers, used by Alembic.
revision = 'a62a425869c7'
down_revision = 'ef60b0d825aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('readable_time', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'readable_time')
    # ### end Alembic commands ###
